# Repository
repo_name: gl-inet/docs3.x
repo_url: https://github.com/gl-inet/docs3.x
edit_uri: ""

site_name: GL.iNet Docs
site_description: Documentation for GL.iNet Productions
site_author: GL.iNet
site_url: https://docs.gl-inet.com/en/3/
site_dir: /home/ubuntu/docs-build/en/3/
copyright: Copyright &copy; 2022 GL Technologies & Microuter Technologies

theme: 
  name: material
  logo: images/logo.svg
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  favicon: images/favicon.png

# Customization
extra:
  analytics:
    provider: google
    property: UA-108265653-5
  social:
    - icon: fontawesome/solid/globe
      link: https://www.gl-inet.com
    - icon: fontawesome/brands/github
      link: https://github.com/gl-inet/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/gl.inet.wifi/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/GLiNetWiFi
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/gl-inet.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCBfNEzurltlIeFFCbUgHQyg
    - icon: fontawesome/brands/pinterest
      link: https://www.pinterest.com/glinetWiFi/
  version:
    provider: mike
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: Japanese
      link: /jp/
      lang: ja

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.css
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/default-skin/default-skin.min.css
  # we can use the cdn or files
  # - stylesheets/photoswipe.min.css
  # - stylesheets/default-skin.min.css
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe-ui-default.min.js
  # we can use the cdn or files
  # - javascripts/photoswipe.min.js
  # - javascripts/photoswipe-ui-default.min.js
  - javascripts/extra.js

markdown_extensions:
  - attr_list
  - pymdownx.tabbed
  - toc:
      permalink: true
  - pymdownx.details

nav:
  - Home:
    - Overview: index.md
  - Specification:
    - Model Category: specification/index.md
    - GL-AR150 (White): specification/gl-ar150/index.md
    - GL-AR300M (Shadow): specification/gl-ar300m/index.md
    - GL-MT300N-V2 (Mango): specification/gl-mt300n-v2/index.md
    - GL-AR750 (Creta): specification/gl-ar750/index.md
    - GL-AR750S-EXT (Slate): specification/gl-ar750s/index.md
    - GL-MT1300 (Beryl): specification/gl-mt1300/index.md
    - GL-SFT1200 (Opal): specification/gl-sft1200/index.md
    - GL-AX1800 (Flint): specification/gl-ax1800/index.md
    - GL-MiFi: specification/gl-mifi/index.md
    - GL-XE300 (Puli): specification/gl-xe300/index.md
    - GL-X750 (Spitz): specification/gl-x750/index.md
    - GL-E750 (Mudi): specification/gl-e750/index.md
    - GL-USB150 (Microuter): specification/gl-usb150/index.md
    - GL-B1300 (Convexa-B): specification/gl-b1300/index.md
    - GL-S1300 (Convexa-S): specification/gl-s1300/index.md
    - GL-MV1000 (Brume): specification/gl-mv1000/index.md
    - GL-MV1000W (Brume-W): specification/gl-mv1000w/index.md
    - GL-X1200 (Amarok): specification/gl-x1200/index.md
    - GL-X300B (Collie): specification/gl-x300b/index.md
    - GL-S10: specification/gl-s10/index.md
    - GL-AP1300 (Cirrus): specification/gl-ap1300/index.md
    - GL-B2200 (Velica): specification/gl-b2200/index.md
    - GL-SF1200: specification/gl-sf1200/index.md
    - microuter-N300: specification/microuter-n300/index.md
    - VIXMINI: specification/vixmini/index.md
    - Domino Core: specification/domino-core/index.md
    - GL-MT300A: specification/gl-mt300a/index.md
    - GL-MT300N: specification/gl-mt300n/index.md
  - Setup:
    - Model Category: setup/index.md
    - Mini Router Series:
      - First Time Setup: setup/mini_router/first_time_setup.md
      - Internet: setup/mini_router/internet.md
      - Wireless: setup/mini_router/wireless.md
      - Clients: setup/mini_router/clients.md
      - Upgrade: setup/mini_router/upgrade.md
      - Firewall: setup/mini_router/firewall.md
      - VPN: setup/mini_router/vpn.md
      - Applications: setup/mini_router/applications.md
      - More Settings: setup/mini_router/more_settings.md
    - GL-AR750 (Creta):
      - First Time Setup: setup/gl-ar750/first_time_setup.md
      - Internet: setup/gl-ar750/internet.md
      - Wireless: setup/gl-ar750/wireless.md
      - Clients: setup/gl-ar750/clients.md
      - Upgrade: setup/gl-ar750/upgrade.md
      - Firewall: setup/gl-ar750/firewall.md
      - VPN: setup/gl-ar750/vpn.md
      - Applications: setup/gl-ar750/applications.md
      - More Settings: setup/gl-ar750/more_settings.md
    - GL-AR750S-EXT (Slate):
      - First Time Setup: setup/gl-ar750s/first_time_setup.md
      - Internet: setup/gl-ar750s/internet.md
      - Wireless: setup/gl-ar750s/wireless.md
      - Clients: setup/gl-ar750s/clients.md
      - Upgrade: setup/gl-ar750s/upgrade.md
      - Firewall: setup/gl-ar750s/firewall.md
      - VPN: setup/gl-ar750s/vpn.md
      - Applications: setup/gl-ar750s/applications.md
      - More Settings: setup/gl-ar750s/more_settings.md
    - GL-MT1300 (Beryl):
      - First Time Setup: setup/gl-mt1300/first_time_setup.md
      - Internet: setup/gl-mt1300/internet.md
      - Wireless: setup/gl-mt1300/wireless.md
      - Clients: setup/gl-mt1300/clients.md
      - Upgrade: setup/gl-mt1300/upgrade.md
      - Firewall: setup/gl-mt1300/firewall.md
      - VPN: setup/gl-mt1300/vpn.md
      - Applications: setup/gl-mt1300/applications.md
      - More Settings: setup/gl-mt1300/more_settings.md
    - GL-SFT1200 (Opal):
      - First Time Setup: setup/gl-sft1200/first_time_setup.md
      - Internet: setup/gl-sft1200/internet.md
      - Wireless: setup/gl-sft1200/wireless.md
      - Clients: setup/gl-sft1200/clients.md
      - Upgrade: setup/gl-sft1200/upgrade.md
      - Firewall: setup/gl-sft1200/firewall.md
      - VPN: setup/gl-sft1200/vpn.md
      - Applications: setup/gl-sft1200/applications.md
      - More Settings: setup/gl-sft1200/more_settings.md
    - GL-AX1800 (Flint):
      - First Time Setup: setup/gl-ax1800/first_time_setup.md
      - Internet: setup/gl-ax1800/internet.md
      - Wireless: setup/gl-ax1800/wireless.md
      - Clients: setup/gl-ax1800/clients.md
      - Upgrade: setup/gl-ax1800/upgrade.md
      - Firewall: setup/gl-ax1800/firewall.md
      - VPN: setup/gl-ax1800/vpn.md
      - Applications: setup/gl-ax1800/applications.md
      - More Settings: setup/gl-ax1800/more_settings.md
    - GL-MiFi:
      - First Time Setup: setup/gl-mifi/first_time_setup.md
      - Internet: setup/gl-mifi/internet.md
      - Wireless: setup/gl-mifi/wireless.md
      - Clients: setup/gl-mifi/clients.md
      - Upgrade: setup/gl-mifi/upgrade.md
      - Firewall: setup/gl-mifi/firewall.md
      - VPN: setup/gl-mifi/vpn.md
      - Applications: setup/gl-mifi/applications.md
      - More Settings: setup/gl-mifi/more_settings.md
    - GL-XE300 (Puli):
      - First Time Setup: setup/gl-xe300/first_time_setup.md
      - Internet: setup/gl-xe300/internet.md
      - Wireless: setup/gl-xe300/wireless.md
      - Clients: setup/gl-xe300/clients.md
      - Upgrade: setup/gl-xe300/upgrade.md
      - Firewall: setup/gl-xe300/firewall.md
      - VPN: setup/gl-xe300/vpn.md
      - Applications: setup/gl-xe300/applications.md
      - More Settings: setup/gl-xe300/more_settings.md
    - GL-X750 (Spitz):
      - First Time Setup: setup/gl-x750/first_time_setup.md
      - Internet: setup/gl-x750/internet.md
      - Wireless: setup/gl-x750/wireless.md
      - Clients: setup/gl-x750/clients.md
      - Upgrade: setup/gl-x750/upgrade.md
      - Firewall: setup/gl-x750/firewall.md
      - VPN: setup/gl-x750/vpn.md
      - Applications: setup/gl-x750/applications.md
      - More Settings: setup/gl-x750/more_settings.md
    - GL-E750 (Mudi):
      - First Time Setup: setup/gl-e750/first_time_setup.md
      - Internet: setup/gl-e750/internet.md
      - Wireless: setup/gl-e750/wireless.md
      - Clients: setup/gl-e750/clients.md
      - Upgrade: setup/gl-e750/upgrade.md
      - Firewall: setup/gl-e750/firewall.md
      - VPN: setup/gl-e750/vpn.md
      - Applications: setup/gl-e750/applications.md
      - More Settings: setup/gl-e750/more_settings.md
    - GL-USB150 (Microuter):
      - First Time Setup: setup/gl-usb150/first_time_setup.md
      - Internet: setup/gl-usb150/internet.md
      - Wireless: setup/gl-usb150/wireless.md
      - Clients: setup/gl-usb150/clients.md
      - Upgrade: setup/gl-usb150/upgrade.md
      - Firewall: setup/gl-usb150/firewall.md
      - VPN: setup/gl-usb150/vpn.md
      - Applications: setup/gl-usb150/applications.md
      - More Settings: setup/gl-usb150/more_settings.md
    - GL-B1300 (Convexa-B):
      - First Time Setup: setup/gl-b1300/first_time_setup.md
      - Internet: setup/gl-b1300/internet.md
      - Wireless: setup/gl-b1300/wireless.md
      - Mesh: setup/gl-b1300/mesh.md
      - Clients: setup/gl-b1300/clients.md
      - Upgrade: setup/gl-b1300/upgrade.md
      - Firewall: setup/gl-b1300/firewall.md
      - VPN: setup/gl-b1300/vpn.md
      - Applications: setup/gl-b1300/applications.md
      - More Settings: setup/gl-b1300/more_settings.md
    - GL-S1300 (Convexa-S):
      - First Time Setup: setup/gl-s1300/first_time_setup.md
      - Internet: setup/gl-s1300/internet.md
      - Wireless: setup/gl-s1300/wireless.md
      - Mesh: setup/gl-s1300/mesh.md
      - Clients: setup/gl-s1300/clients.md
      - Upgrade: setup/gl-s1300/upgrade.md
      - Firewall: setup/gl-s1300/firewall.md
      - VPN: setup/gl-s1300/vpn.md
      - Applications: setup/gl-s1300/applications.md
      - More Settings: setup/gl-s1300/more_settings.md
    - GL-B2200 (Velica):
      - First Time Setup: setup/gl-b2200/first_time_setup.md
      - Internet: setup/gl-b2200/internet.md
      - Mesh / Wireless: setup/gl-b2200/wireless.md
      - Clients: setup/gl-b2200/clients.md
      - Upgrade: setup/gl-b2200/upgrade.md
      - Firewall: setup/gl-b2200/firewall.md
      - VPN: setup/gl-b2200/vpn.md
      - Applications: setup/gl-b2200/applications.md
      - More Settings: setup/gl-b2200/more_settings.md
    - GL-MV1000 (Brume):
      - First Time Setup: setup/gl-mv1000/first_time_setup.md
      - Internet: setup/gl-mv1000/internet.md
      - Wireless: setup/gl-mv1000/wireless.md
      - Clients: setup/gl-mv1000/clients.md
      - Upgrade: setup/gl-mv1000/upgrade.md
      - Firewall: setup/gl-mv1000/firewall.md
      - VPN: setup/gl-mv1000/vpn.md
      - Applications: setup/gl-mv1000/applications.md
      - More Settings: setup/gl-mv1000/more_settings.md
    - GL-MV1000W (Brume-W):
      - First Time Setup: setup/gl-mv1000w/first_time_setup.md
      - Internet: setup/gl-mv1000w/internet.md
      - Wireless: setup/gl-mv1000w/wireless.md
      - Clients: setup/gl-mv1000w/clients.md
      - Upgrade: setup/gl-mv1000w/upgrade.md
      - Firewall: setup/gl-mv1000w/firewall.md
      - VPN: setup/gl-mv1000w/vpn.md
      - Applications: setup/gl-mv1000w/applications.md
      - More Settings: setup/gl-mv1000w/more_settings.md
    - GL-SF1200:
      - First Time Setup: setup/gl-sf1200/first_time_setup.md
      - Internet: setup/gl-sf1200/internet.md
      - Wireless: setup/gl-sf1200/wireless.md
      - Clients: setup/gl-sf1200/clients.md
      - Upgrade: setup/gl-sf1200/upgrade.md
      - Firewall: setup/gl-sf1200/firewall.md
      - VPN: setup/gl-sf1200/vpn.md
      - Applications: setup/gl-sf1200/applications.md
      - More Settings: setup/gl-sf1200/more_settings.md
    - GL-X1200 (Amarok):
      - First Time Setup: setup/gl-x1200/first_time_setup.md
    - GL-X300B (Collie):
      - First Time Setup: setup/gl-x300b/first_time_setup.md
    - GL-S10:
      - First Time Setup: setup/gl-s10/first_time_setup.md
      - User Manual: setup/gl-s10/user_manual.md
      - Firmware Complilation Guide: setup/gl-s10/firmware_compilation_guide.md
    - GL-AP1300/GL-AP1300LTE (Cirrus):
      - First Time Setup: setup/gl-ap1300/first_time_setup.md
      - Internet: setup/gl-ap1300/internet.md
      - Wireless: setup/gl-ap1300/wireless.md
      - Clients: setup/gl-ap1300/clients.md
      - Upgrade: setup/gl-ap1300/upgrade.md
      - Firewall: setup/gl-ap1300/firewall.md
      - VPN: setup/gl-ap1300/vpn.md
      - Applications: setup/gl-ap1300/applications.md
      - More Settings: setup/gl-ap1300/more_settings.md
    - microuter-N300:
      - First Time Setup: setup/microuter-n300/first_time_setup.md
      - Internet: setup/microuter-n300/internet.md
      - Wireless: setup/microuter-n300/wireless.md
      - Clients: setup/microuter-n300/clients.md
      - Upgrade: setup/microuter-n300/upgrade.md
      - Firewall: setup/microuter-n300/firewall.md
      - VPN: setup/microuter-n300/vpn.md
      - Applications: setup/microuter-n300/applications.md
      - More Settings: setup/microuter-n300/more_settings.md
    - VIXMINI:
      - First Time Setup: setup/vixmini/first_time_setup.md
      - Internet: setup/vixmini/internet.md
      - Wireless: setup/vixmini/wireless.md
      - Clients: setup/vixmini/clients.md
      - Upgrade: setup/vixmini/upgrade.md
      - Applications: setup/vixmini/applications.md
      - More Settings: setup/vixmini/more_settings.md
  - Tutorials:
    - Overview: tutorials/index.md
    - Repeater: tutorials/repeater.md
    - Turn off Wi-Fi: tutorials/turn_off_wifi.md
    - Produce a wired connection: tutorials/produce_a_wired_connection.md
    - Connect to an existing Wi-Fi: tutorials/connect_to_an_existing_wifi.md
    - Hide SSID: tutorials/hide_ssid.md
    - Setup as a bridge: tutorials/setup_the_router_as_a_bridge.md
    - Firmware Upgrade: tutorials/firmware_upgrade.md
    - Check Firmware Version: tutorials/check_firmware_version.md
    - What is web Admin Panel: tutorials/web_admin_panel.md
    - SSH to the Router: tutorials/ssh.md
    - Extensible Authentication Protocol: tutorials/eap.md
    - Modify files on the router: tutorials/scp.md
    - OpenVPN Client: tutorials/openvpn_client.md
    - OpenVPN Server: tutorials/openvpn_server.md
    - OpenVPN Bridge: tutorials/openvpn_bridge.md
    - WireGuard Client: tutorials/wireguard_client.md
    - WireGuard Server: tutorials/wireguard_server.md
    - Internet Kill Switch: tutorials/internet_kill_switch.md
    - Change WAN to LAN: tutorials/change_wan_to_lan.md
    - LED Indicators: tutorials/led.md
    - VPN Policies: tutorials/vpn_policies.md
    - Protect Privacy: tutorials/how_to_use_vpn_and_dns_encryption_to_protect_your_privacy_with_glinet_router.md
    - File Sharing: tutorials/file_sharing.md
    - Multimedia File Sharing: tutorials/multimedia_file_sharing.md
    - IPv6: tutorials/ipv6.md
    - DDNS: tutorials/ddns.md
    - Cloud: tutorials/cloud.md
    - Cloudflare: tutorials/how_to_use_cloudflare_dns_over_tls_on_glinet_router.md
    - NextDNS: tutorials/nextdns.md
    - Firewall: tutorials/firewall.md
    - Check IP Address: tutorials/how_to_check_if_isp_assigns_you_a_public_ip_address.md
    - Internet Priority: tutorials/internet_connection_priority.md
    - Mobile App: tutorials/mobile_app.md
    - LuCI: tutorials/what_is_luci.md
    - Find model number: tutorials/how_to_find_model.md 
    - Cells Info: tutorials/cells_info.md
    - SMS: tutorials/sms.md
    - SMS Forward: tutorials/sms_forward.md
    - LED Customization: tutorials/led_customization.md
    - Setup Captive Portal: tutorials/captive_portal.md
    - Connect to Captive Portal: tutorials/connect_to_a_hotspot_with_captive_portal.md
    - EasyTether: tutorials/tether.md
    - Tor: tutorials/tor.md
    - Camera: tutorials/camera.md
  - Troubleshooting:
    - Overview: troubleshooting/index.md
    - Can't access web Admin Panel: troubleshooting/cannot_access_web_admin_panel.md
    - Repair or Reset: troubleshooting/reset.md
    - Debrick via Uboot: troubleshooting/debrick.md
    - Repeat Failure: troubleshooting/repeat_failure.md
    - Can't find SSID: troubleshooting/cannot_find_ssid.md
    - Override DNS not take effect: troubleshooting/override_dns_settings_for_all_clients_not_take_effect.md
    - GoodCloud issues: troubleshooting/goodcloud.md
    - Modem FAQ: troubleshooting/modem_faq.md
    - FAQs: troubleshooting/faq.md
  - Development:
    - UART Serial: dev/serial.md
    - Advanced Uboot: dev/uboot.md
    - BLE MQTT Bridge: dev/ble2mqtt.md